name: 'imdb_analytics'
version: '1.0.0'
config-version: 2

profile: 'my_imdb_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  imdb_analytics:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table

require-dbt-version: ">=1.0.0,<2.0.0"

packages:
  - package: dbt-labs/dbt_utils
    version: ">=0.7.0,<2.0.0"
