
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5434:5432"

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./scripts/airflow-entrypoint.sh
    command: version
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config/security:/opt/airflow/config/security 
      - ./airflow-logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./scripts/airflow-entrypoint.sh
    command: scheduler
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8794:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config/security:/opt/airflow/config/security 
      - ./airflow-logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 2

  webserver:
    hostname: webserver
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./scripts/airflow-entrypoint.sh
    command: webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__WEBSERVER__SECURITY_MANAGER_CLASS=config.security.override_security_manager.CustomSecurityManager

    volumes:
      - ./dags:/opt/airflow/dags
      - ./config/security:/opt/airflow/config/security 
      - ./airflow-logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 2