my_imdb_project:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 4
  target: dev
