my_imdb_project:
  outputs:
    dev:
      type: postgres
      host: postgres #in case of dbt docs comand trouble use localhost
      user: airflow
      pass: airflow
      port: 5433
      dbname: airflow
      schema: public
      threads: 4
  target: dev
