version: 2

models:
  - name: stg_title_basics
    description: "Staging model for IMDb title basics"
    columns:
      - name: tconst
        description: "Unique identifier for the title"
        tests:
          - not_null
          - unique

      - name: primary_title
        description: "Primary title of the work"
        tests:
          - not_null

      - name: original_title
        description: "Original title of the work"

      - name: is_adult
        description: "True if adult content"
        tests:
          - accepted_values:
              values: [true, false]

      - name: start_year
        description: "Year the title started"
        tests: 
          - not_null

      - name: end_year
        description: "Year the title ended"

      - name: runtime_minutes
        description: "Duration of the title"

      - name: primary_genre
        description: "First genre tag"
        tests: 
          - not_null

      - name: secondary_genre
        description: "Second genre tag"

      - name: third_genre
        description: "Third genre tag"

  - name: stg_title_crew_directors
    description: "Normalized view of directors for each title from the raw title_crew table."
    columns:
      - name: tconst
        description: "Unique identifier for the title"
        tests:
          - not_null

      - name: director
        description: "Director name; individual director extracted from the raw data."
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - tconst
            - director

  - name: stg_title_crew_writers
    description: "Normalized view of writers for each title from the raw title_crew table."
    columns:
      - name: tconst
        description: "Unique identifier for the title"
        tests:
          - not_null
      - name: writer
        description: "Writer name; individual writer extracted from the raw data."
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - tconst
            - writer
  
  - name: stg_title_episode
    description: "Staging model for IMDb title episode data"
    columns:
      - name: tconst
        description: "Unique identifier of the episode"
        tests:
          - not_null

      - name: parent_tconst
        description: "Unique identifier of the parent TV Series"
        tests:
          - not_null
  
      - name: season_number
        description: "Season number of the episode"

      - name: episode_number
        description: "Episode number within the season"

  - name: stg_title_principals
    description: "Staging model for IMDb title principals data"
    columns:
      - name: tconst
        description: "Unique identifier for the title"

      - name: ordering
        description: "Unique identifier within the same TitleID"

      - name: nconst
        description: "Unique identifier for the name"

      - name: category
        description: "Job category(e.g., actor, actress, etc.)"
        tests:
          - not_null

      - name: job
        description: "Specific job title within the category"

      - name: characters
        description: "Character name"

  - name: stg_title_ratings
    description: "Staging model for IMDb title ratings data"
    columns:
      - name: tconst
        description: "Unique identifier of the title"
        tests:
          - unique

      - name: average_rating
        description: "Weighted average of user ratings"
        tests:
          - not_null

      - name: num_votes
        description: "Number of votes received for a title"
        tests:
          - not_null

  - name: stg_name_basics
    description: "Staging model for IMDb name basics data"
    columns:
      - name: nconst
        description: "Unique identifier for the person"
        tests:
          - unique

      - name: primary_name
        description: "Primary name of the person"
        tests:
          - not_null:
              severity: warn  # Make this a warning instead of error

      - name: birth_year
        description: "Year of birth"

      - name: death_year
        description: "Year of death"

      - name: first_profession
        description: "First profession of the person"
        tests:
          - not_null:
              severity: warn  # Make this a warning instead of error
      - name: second_profession
        description: "Second profession of the person"
      - name: third_profession
        description: "Third profession of the person"
      
      - name: first_title_known_for
        description: "First title the person is known for"
        tests:
          - not_null:
              severity: warn  # Make this a warning instead of error
      - name: second_title_known_for
        description: "Second title the person is known for"
      - name: third_title_known_for
        description: "Third title the person is known for"
      - name: fourth_title_known_for
        description: "Fourth title the person is known for"
    

        




